server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: plant-service
          uri: lb://plant-service
          predicates:
            - Path=/plant-service/**
          filters:
            - StripPrefix=1



        - id: specimen-service
          uri: lb://specimen-service
          predicates:
            - Path=/specimen-service/**
          filters:
              - StripPrefix=1

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/
      register-with-eureka: true
      fetch-registry: true
    instance:
      prefer-ip-address: true
