spring:
  application:
    name: plant-service # sau specimen-service, etc.
  cloud:
    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8080  # sau alt port
